### ISSUE TITLE
Uses AWS_ACCESS_KEY_ID and not AWS_SES_ACCESS_KEY_ID when both set

### ISSUE THREAD

**Issue by jjorissen52** [azavea/django-amazon-ses#34]
I am using two separate access keys in my project: one which has access to my media bucket and one which has access to SES.

When I have both keys set in my project, I get a traceback.
```
AWS_ACCESS_KEY_ID = config.get("s3_storage", "aws_access_key_id")
AWS_SECRET_ACCESS_KEY = config.get("s3_storage", "aws_secret_access_key")

# DJANGO SES
EMAIL_BACKEND = 'django_amazon_ses.EmailBackend'
AWS_DEFAULT_REGION = 'us-east-1'
AWS_SES_ACCESS_KEY_ID = config.get('ses', 'email_host_user')
AWS_SES_SECRET_ACCESS_KEY = config.get('ses', 'email_host_password')
AWS_SES_REGION = 'us-east-1'
EMAIL_HOST_USER = config.get('django', 'email_host_user')
SUPPORT_EMAIL = config.get('django', 'support_email')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
```

> botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the SendRawEmail operation: User '{my_bucket_user_arn}' is not authorized to perform 'ses:SendRawEmail' on resource '{some_amazon_arn}:identity/no-reply@mydomain.com'
[14/Mar/2018 15:25:57] "POST /accounts/login/ HTTP/1.1" 500 136132

When I comment out 

```
AWS_ACCESS_KEY_ID = config.get("s3_storage", "aws_access_key_id")
AWS_SECRET_ACCESS_KEY = config.get("s3_storage", "aws_secret_access_key")
```
everything works as expected.

I think this is happening because of the `__init__` method in `django_amazon_ses.py`, which just uses `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` when they are supplied instead of first checking for `AWS_SES_ACCESS_KEY_ID` and `AWS_SES_SECRET_ACCESS_KEY`.

```
 def __init__(self, fail_silently=False, **kwargs):
        """Creates a client for the Amazon SES API.

        Args:
            fail_silently: Flag that determines whether Amazon SES
                client errors should throw an exception.

        """
        super(EmailBackend, self).__init__(fail_silently=fail_silently)
        access_key_id = getattr(settings, 'AWS_ACCESS_KEY_ID', None)
        secret_access_key = getattr(settings, 'AWS_SECRET_ACCESS_KEY', None)
        region_name = getattr(settings, 'AWS_DEFAULT_REGION', 'us-east-1')
        self.conn = boto3.client(
            'ses',
            aws_access_key_id=access_key_id,
            aws_secret_access_key=secret_access_key,
            region_name=region_name,
        )
``` 
How do I make it use my SES_ACCESS_KEY instead of my regular ACCESS_KEY?

**Comment by jjorissen52** [comment]
Seems that this PR is trying to address the issue.
https://github.com/azavea/django-amazon-ses/pull/32

**Comment by hectcastro** [comment]
After merging https://github.com/azavea/django-amazon-ses/pull/32 to `develop`, I ran tests to try and reproduce your example with this diff applied:

```diff
diff --git a/CHANGELOG.rst b/CHANGELOG.rst
index 5d89478..aac149f 100644
--- a/CHANGELOG.rst
+++ b/CHANGELOG.rst
@@ -4,6 +4,7 @@ UNRELEASED
 - Remove support for Django < 1.11.
 - Add ``AWS_SES_*`` settings to configure AWS credentials through
   ``settings.py``.
+- Add ``EmailBackend`` constructor arguments to override AWS credentials.
 
 1.0.0 - 2017-12-07
 ==================
diff --git a/django_amazon_ses.py b/django_amazon_ses.py
index e984a00..2da2ee6 100644
--- a/django_amazon_ses.py
+++ b/django_amazon_ses.py
@@ -20,7 +20,7 @@ class EmailBackend(BaseEmailBackend):
     """
 
     def __init__(self, fail_silently=False, aws_access_key_id=None,
-                 aws_secret_access_key=None, ** kwargs):
+                 aws_secret_access_key=None, **kwargs):
         """Creates a client for the Amazon SES API.
 
         Args:
@@ -30,24 +30,27 @@ class EmailBackend(BaseEmailBackend):
         """
         super(EmailBackend, self).__init__(fail_silently=fail_silently)
 
-        # Get configuration from AWS default settings
+        # Get configuration from AWS prefixed settings in settings.py
         access_key_id = getattr(settings, 'AWS_ACCESS_KEY_ID', None)
         secret_access_key = getattr(settings, 'AWS_SECRET_ACCESS_KEY', None)
         region_name = getattr(settings, 'AWS_DEFAULT_REGION', 'us-east-1')
 
-        # Override configuration with AWS SES-specific settings
+        # Override AWS prefixed configuration with Amazon SES-specific settings
         access_key_id = getattr(settings, 'AWS_SES_ACCESS_KEY_ID',
                                 access_key_id)
         secret_access_key = getattr(settings, 'AWS_SES_SECRET_ACCESS_KEY',
                                     secret_access_key)
         region_name = getattr(settings, 'AWS_SES_REGION', region_name)
 
-        # Override if configuration are provided through constructor
-        if (aws_access_key_id is not None and
-                aws_secret_access_key is not None):
+        # Override all previous configuration if settings provided
+        # through the constructor
+        if aws_access_key_id is not None and aws_secret_access_key is not None:
             access_key_id = aws_access_key_id
             secret_access_key = aws_secret_access_key
 
+        raise Exception('Access Key: {}\nSecret Key: {}'.format(
+            access_key_id, secret_access_key))
+
         self.conn = boto3.client(
             'ses',
             aws_access_key_id=access_key_id,
```

(The only relevant bit is the addition of `raise`. Also, note the code I'm testing on `develop` is unreleased—it is different than 1.0.0.)

With the following code in a view:

```python
def index(request):
    send_mail(
        'Subject here',
        'Here is the message.',
        'from@example.com',
        ['to@example.com'],
        fail_silently=False,
    )
```

And `settings.py` with:

```python
AWS_ACCESS_KEY_ID = '1'
AWS_SECRET_ACCESS_KEY = '1'
AWS_DEFAULT_REGION = '1'

EMAIL_BACKEND = 'django_amazon_ses.EmailBackend'

AWS_SES_ACCESS_KEY_ID = '2'
AWS_SES_SECRET_ACCESS_KEY = '2'
AWS_SES_REGION = '2'
```

When that view is executed, this trace produced is:

```
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
app_1  |     response = get_response(request)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
app_1  |     response = self.process_exception_by_middleware(e, request)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
app_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1  |   File "/usr/src/app/test/home/views.py", line 12, in index
app_1  |     fail_silently=False,
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/__init__.py", line 54, in send_mail
app_1  |     fail_silently=fail_silently,
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/__init__.py", line 35, in get_connection
app_1  |     return klass(fail_silently=fail_silently, **kwds)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django_amazon_ses.py", line 52, in __init__
app_1  |     access_key_id, secret_access_key))
app_1  | Exception: Access Key: 2
app_1  | Secret Key: 2
```

If I uncomment the `AWS_SES_` prefixed settings in `settings.py`, I get:

```
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
app_1  |     response = get_response(request)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
app_1  |     response = self.process_exception_by_middleware(e, request)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
app_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1  |   File "/usr/src/app/test/home/views.py", line 12, in index
app_1  |     fail_silently=False,
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/__init__.py", line 54, in send_mail
app_1  |     fail_silently=fail_silently,
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/__init__.py", line 35, in get_connection
app_1  |     return klass(fail_silently=fail_silently, **kwds)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django_amazon_ses.py", line 52, in __init__
app_1  |     access_key_id, secret_access_key))
app_1  | Exception: Access Key: 1
app_1  | Secret Key: 1
```

Lastly, if I alter the code in the view so that it uses `get_connection()` to create an instance of the email backend with:

```python
def index(request):
    with mail.get_connection(aws_access_key_id='3',
                             aws_secret_access_key='3') as connection:
        mail.EmailMessage(
            'Subject here',
            'Here is the message.',
            'from@example.com',
            ['to@example.com'],
            connection=connection,
        ).send()
```

I get:

```
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
app_1  |     response = get_response(request)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
app_1  |     response = self.process_exception_by_middleware(e, request)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
app_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1  |   File "/usr/src/app/test/home/views.py", line 16, in index
app_1  |     aws_secret_access_key='3') as connection:
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/__init__.py", line 35, in get_connection
app_1  |     return klass(fail_silently=fail_silently, **kwds)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django_amazon_ses.py", line 52, in __init__
app_1  |     access_key_id, secret_access_key))
app_1  | Exception: Access Key: 3
app_1  | Secret Key: 3
```

Things appear to behave as expected. I also made sure to use a clean containerized environment to test (one without any existing AWS authentication mechanisms like `AWS_PROFILE` or instance metadata present).

**Comment by jjorissen52** [comment]
https://github.com/azavea/django-amazon-ses/pull/32 resolves the issue.

**Comment by nikksbagul** [comment]
When you release this update.

**Comment by hectcastro** [comment]
The 2.0.0 release was just published. Please see the `CHANGELOG` for details: https://pypi.python.org/pypi/django-amazon-ses
